[features]
seeds = false
skip-lint = false
[programs.localnet]
wallet_tracker = "TRCKTiWtWCzCopm4mnR47n4v2vEvjRQ1q6rsDxRUbVR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kelliott/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 100000